"""empty message

Revision ID: 7f87736a5f8f
Revises: 1bf3c45fdc56
Create Date: 2026-02-04 18:31:58.313404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f87736a5f8f'
down_revision = '1bf3c45fdc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=True))
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('favorite_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('favorite_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorite_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_favorite_user_id'))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
